spring.application.name=sb-ecom
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:f1da265e-9d0f-49fd-a6d4-5f3afb345d83
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=create-drop